<a href="https://colab.research.google.com/github/HuynPann511/MACHINE_LEARNING_HK241/blob/main/Practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Practice 2 - Chapter 2: Build a model which predicts sales based on the money spent on different platforms for marketing

In [9]:
import pandas as pd
import numpy as np

theta_0 = 0 #define the bias of Hypothesis function

# Read CSV file
file_path = "/content/Practice2_Chapter2.csv"
df = pd.read_csv(file_path)

# export value of data to x and y
x = df[['TV', 'Radio', 'Newspaper']].values
y = df['Sales'].values
print("Giá trị của data:", x)
print("Giá trị của output:\n", y)

Giá trị của data: [[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]
 [  8.7  48.9  75. ]
 [ 57.5  32.8  23.5]
 [120.2  19.6  11.6]
 [  8.6   2.1   1. ]
 [199.8   2.6  21.2]
 [ 66.1   5.8  24.2]
 [214.7  24.    4. ]
 [ 23.8  35.1  65.9]
 [ 97.5   7.6   7.2]
 [204.1  32.9  46. ]
 [195.4  47.7  52.9]
 [ 67.8  36.6 114. ]
 [281.4  39.6  55.8]
 [ 69.2  20.5  18.3]
 [147.3  23.9  19.1]
 [218.4  27.7  53.4]
 [237.4   5.1  23.5]
 [ 13.2  15.9  49.6]
 [228.3  16.9  26.2]
 [ 62.3  12.6  18.3]
 [262.9   3.5  19.5]
 [142.9  29.3  12.6]
 [240.1  16.7  22.9]
 [248.8  27.1  22.9]
 [ 70.6  16.   40.8]
 [292.9  28.3  43.2]
 [112.9  17.4  38.6]
 [ 97.2   1.5  30. ]
 [265.6  20.    0.3]
 [ 95.7   1.4   7.4]
 [290.7   4.1   8.5]
 [266.9  43.8   5. ]
 [ 74.7  49.4  45.7]
 [ 43.1  26.7  35.1]
 [228.   37.7  32. ]
 [202.5  22.3  31.6]
 [177.   33.4  38.7]
 [293.6  27.7   1.8]
 [206.9   8.4  26.4]
 [ 25.1  25.7  43.3]
 [175.1  22.5  31.5]
 [ 89.7   9.9  3

In [17]:
# Feature scaling
# This function is using to determine the scale of each column (for each feature of data)
def feature_scaling(x):
    mean_val = np.mean(x, axis=0) # axis = 0 means evaluate value of each column
    max_val = np.max(x, axis=0)
    x_scaled = np.abs((x - mean_val) / max_val)
    return x_scaled, mean_val, max_val

x_scaled, mean_val, max_val = feature_scaling(x)
print(f'giá trị x scaled {x_scaled}')
print(f'giá trị mean {mean_val}')


# Initialize parameters
theta = np.zeros(x_scaled.shape[1])  # [theta_0, theta_1, ..., theta_n]
learning_rate = 0.01
n = 5000 # n: number of interactions

def hypothesis(x, theta):
    return np.dot(x, theta) + theta_0

def cost_function(x, y, theta):
    m = len(y)
    predictions = hypothesis(x, theta)
    return (1 / (2 * m)) * np.sum((predictions - y) ** 2)

def gradient_descent(x, y, theta, learning_rate, n):
    m = len(y)
    history = {"theta": [], "cost": []}

    for i in range(n):
        # Compute gradients
        predictions = hypothesis(x, theta)
        gradients = (1 / m) * np.dot(x.T, (predictions - y))

        # Update theta
        theta = theta - learning_rate * gradients

        # Save cost and theta for tracking
        cost = cost_function(x, y, theta)
        history["theta"].append(theta)
        history["cost"].append(cost)


    return theta, history

# Train the model using gradient descent
theta, history = gradient_descent(x_scaled, y, theta, learning_rate, n)

# Make predictions
predicted_sales = hypothesis(x_scaled, theta)

# Inverse scaling
def inverse_scaling(theta, mean_val, max_val):
    # Ensure mean_val and max_val are sliced to match features
    mean_val = mean_val[:len(theta)-1]
    max_val = max_val[:len(theta)-1]

    # Compute theta_original
    theta_original = np.zeros_like(theta)
    theta_original[0] = theta[0] - np.sum((theta[1:] * mean_val) / max_val)
    theta_original[1:] = theta[1:] / max_val

    return theta_original

theta_original = inverse_scaling(theta, mean_val, max_val)

# Print results
print(f"Final scaled theta: {theta}")
print(f"Final original theta: {theta_original}")
print(f"Predicted sales: {predicted_sales}")



giá trị x scaled [[2.80220985e-01 2.93064516e-01 3.39000000e-01]
 [3.45959852e-01 3.23306452e-01 1.27596491e-01]
 [4.38065115e-01 4.56370968e-01 3.39877193e-01]
 [1.50387989e-02 3.63629032e-01 2.45140351e-01]
 [1.13891700e-01 2.51290323e-01 2.44263158e-01]
 [4.66742578e-01 5.16854839e-01 3.89877193e-01]
 [3.02100202e-01 1.92258065e-01 6.18771930e-02]
 [9.05617409e-02 7.38709677e-02 1.66263158e-01]
 [4.67079960e-01 4.26693548e-01 2.59245614e-01]
 [1.77994265e-01 4.16612903e-01 8.20526316e-02]
 [2.73085358e-01 3.52096774e-01 5.57368421e-02]
 [2.28264170e-01 1.48387097e-02 2.32929825e-01]
 [4.15797908e-01 2.38629032e-01 3.10052632e-01]
 [1.67147436e-01 3.15806452e-01 2.04859649e-01]
 [1.92501687e-01 1.94274194e-01 1.35491228e-01]
 [1.63149460e-01 4.92661290e-01 1.96017544e-01]
 [2.67349865e-01 2.68870968e-01 7.31982456e-01]
 [4.53297908e-01 3.29354839e-01 2.21456140e-01]
 [2.62626518e-01 5.57258065e-02 1.07491228e-01]
 [8.68758435e-04 1.28225806e-02 1.00473684e-01]
 [2.40747301e-01 8.9435